[package]
name = "embed-resource-msvc-test"
version = "0.0.0"
edition = "2024"
build = "build.rs"
workspace = "../../.."

[[bin]]
name = "embed-resource-msvc-test"
path = "main.rs"

[build-dependencies]
embed-resource.path = "../../.."
